// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKTO_07nuYNQ15HKEfRbFskwPzxn_s2fI',
    appId: '1:557477536716:web:9adcdf32e00e469c113369',
    messagingSenderId: '557477536716',
    projectId: 'symbians-820b0',
    authDomain: 'symbians-820b0.firebaseapp.com',
    storageBucket: 'symbians-820b0.firebasestorage.app',
    measurementId: 'G-XNWYYJHJD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCotmVFYdZqdZthXQZe9is9vmS7pz-TqsI',
    appId: '1:557477536716:android:4fff2483e942ac3d113369',
    messagingSenderId: '557477536716',
    projectId: 'symbians-820b0',
    storageBucket: 'symbians-820b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPFcMR7Wo-LiB0aMO98SJqdaWV711x-eg',
    appId: '1:557477536716:ios:0be90aa143c9f13b113369',
    messagingSenderId: '557477536716',
    projectId: 'symbians-820b0',
    storageBucket: 'symbians-820b0.firebasestorage.app',
    iosBundleId: 'ng.anto.formation',
  );
}
