name: symbians
description: "Symbians - AI-powered solana app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Navigation
  auto_route: 10.1.2

  # State Management
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  equatable: ^2.0.7

  # Immutable Models & Serialization
  freezed_annotation: any
  json_annotation: ^4.9.0

  # Backend
  supabase_flutter: ^2.9.1

  # Environment
  envied: ^1.1.1

  # UI
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.3.2
  flutter_animate: ^4.5.2
  flutter_styled_toast: ^2.2.1
  crystal_navigation_bar: ^1.0.0

  # Auth
  google_sign_in: ^7.2.0

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  share_plus: ^11.0.0
  timeago: ^3.7.1
  app_links: ^6.4.1
  file_picker: ^8.1.5

  # Solana (Web3 flavor)
  solana_mobile_client: ^0.1.2
  solana: ^0.31.2+1

  # Game Engine
  flame: ^1.18.0
  firebase_core: ^4.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: any
  auto_route_generator: any
  json_serializable: any
  freezed: any
  envied_generator: any

  # Asset Generation
  flutter_gen: any
  flutter_gen_runner: any

  # App Icons
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/brand/
    - assets/sprites/
    - assets/sprites/grass/

flutter_gen:
  output: lib/gen/
  line_length: 80
  # Optional
  integrations:
    flutter_svg: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/brand/symbians_white.png"

flutter_native_splash:
  color: "#000000"
  image: assets/brand/symbians_black.png
  android_12:
    color: "#000000"
    image: assets/brand/symbians_black.png